version: '3.2'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '1337:80'
    depends_on:
      - backend
      - frontend
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - type: volume
        source: backend_volume
        target: /app/node_modules
      - type: bind
        source: ./backend
        target: /app
    env_file:
      - .env
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - type: volume
        source: frontend_volume
        target: /app/node_modules
      - type: bind
        source: ./frontend
        target: /app

volumes:
  frontend_volume:
  backend_volume:
